import { NextResponse } from 'next/server';

import { prisma } from '@/lib/prisma';
import { requireFeatureAccess } from '@/lib/authz/server';
import { assertOrgScoped } from '@/lib/phi-access';

export const runtime = 'nodejs';

/**
 * GET /api/notes/[id]/artifacts
 *
 * Returns NoteArtifact rows (patient handout, referral letter) for a
 * signed note. Sprint 0.7 — these are generated by the post-sign
 * artifacts worker but were not previously exposed to any UI. The
 * /visits/[noteId] viewer reads them via this endpoint.
 *
 * Auth follows the same pattern as GET /api/notes/[id]: requireFeatureAccess
 * + org scope + clinician ownership (admins + VIEWER allowed).
 */
export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const guard = await requireFeatureAccess('NOTE_REVIEW');
  if ('error' in guard) return guard.error;
  const { authorizationUser } = guard;

  const { id } = await params;

  const note = await prisma.note.findFirst({
    where: { id, orgId: authorizationUser.orgId },
    select: { id: true, orgId: true, clinicianOrgUserId: true, status: true },
  });
  if (!note) return NextResponse.json({ error: { code: 'not_found' } }, { status: 404 });
  assertOrgScoped(note.orgId, authorizationUser.orgId);

  if (
    note.clinicianOrgUserId !== authorizationUser.orgUserId &&
    authorizationUser.role !== 'ORG_ADMIN' &&
    authorizationUser.role !== 'VIEWER'
  ) {
    return NextResponse.json({ error: { code: 'forbidden' } }, { status: 403 });
  }

  const artifacts = await prisma.noteArtifact.findMany({
    where: { noteId: note.id },
    orderBy: { generatedAt: 'asc' },
    select: {
      id: true,
      kind: true,
      content: true,
      generatedAt: true,
    },
  });

  return NextResponse.json({
    data: {
      artifacts: artifacts.map((a) => ({
        id: a.id,
        kind: a.kind,
        content: a.content,
        generatedAt: a.generatedAt.toISOString(),
      })),
    },
  });
}
