import type { Job } from 'bullmq';
import { Prisma, NoteStatus, Division } from '@prisma/client';

import { prisma } from '@/lib/prisma';
import { writeAuditLog } from '@/lib/audit/log';
import { enqueueCaseRouterJob, enqueueCleoStateRefresh } from '@/lib/queue';
import { getLLMService } from '@/services/llm';
import { stripJsonFence } from '@/lib/llm/strip-json-fence';
import { buildMasterPrompt, buildSectionPrompt, type NoteSectionDef } from '@/lib/notes/build-prompt';
import { projectPatientForPrompt, projectEpisodeForPrompt } from '@/lib/notes/projections';
import { PERSONA_VERSION } from '@/services/copilot/persona';
import {
  markSectionStatus,
  appendRegeneration,
  mergeSectionIntoDraft,
  recordSectionAttempt,
} from '@/lib/notes/section-status';
import { markNoteEmptyTranscript } from '@/lib/notes/empty-transcript';
import type { TranscriptClean } from '@/services/transcription';
import { randomBytes } from 'node:crypto';

type GenerateNoteJob = {
  noteId: string;
  orgId: string;
  type: 'generate-note';
  requestId: string;
};

type RegenerateSectionJob = {
  noteId: string;
  orgId: string;
  type: 'regenerate-section';
  requestId: string;
  sectionId: string;
  triggeredByUserId?: string;
  overwroteEdited?: boolean;
};

type AnalyzeFlagsJob = {
  noteId: string;
  orgId: string;
  type: 'analyze-flags';
  requestId: string;
};

type AiGenerationJob = GenerateNoteJob | RegenerateSectionJob | AnalyzeFlagsJob;

/**
 * ai-generation worker (spec §E).
 *
 * Two job types share this handler via the type discriminator:
 *
 *   1. generate-note — loops over template.sectionSchema.sections, generates
 *      each section via LLM (PHI guard runs), marks _sectionStatus per
 *      section, merges content into draftJson. On success: flips DRAFTING
 *      → DRAFT and audits NOTE_GENERATION_COMPLETED. A single failed
 *      section doesn't tank the whole job — that section gets status
 *      'failed' and the loop continues.
 *
 *   2. regenerate-section — single section. Marks generating → populated,
 *      replaces only the target key in draftJson, appends a _regenerations
 *      entry capturing who/when/what.
 *
 * Anti-regression rule 3: refuses if Note.status === SIGNED. finalJson
 * is owned exclusively by the sign route (Commit 8).
 *
 * Idempotent: queue.ts uses stable jobIds so duplicate enqueues collapse.
 * The handler is also safe to retry — already-populated sections are
 * regenerated by generate-note (which is OK; final state is the same).
 */
export async function handle(job: Job<AiGenerationJob>) {
  // Unit 14: analyze-flags has its own load path (no patient/episode
  // projections needed, and the writes target ReviewFlag not draftJson).
  // Delegate before the heavy load below.
  if (job.data.type === 'analyze-flags') {
    const mod = await import('./analyze-flags-handler');
    return mod.handleAnalyzeFlags(job as unknown as Job<AnalyzeFlagsJob>);
  }

  const { noteId, orgId, type, requestId } = job.data;

  const note = await prisma.note.findFirst({
    where: { id: noteId, orgId },
    include: {
      template: true,
      patient: true,
      encounter: { include: { episode: { include: { department: true, goals: true } } } },
    },
  });
  if (!note) {
    console.warn(`[ai-generation] note ${noteId} not found — dropping`);
    return { skipped: 'not_found' };
  }
  if (note.status === NoteStatus.SIGNED) {
    return { skipped: 'signed' };
  }
  // Idempotency: a generate-note retry on a note that already reached DRAFT
  // would re-walk the section loop and look like a regeneration storm to the
  // clinician on /review. Restyle resets status to DRAFTING before enqueueing
  // so it still re-runs; other callers should rely on regenerate-section for
  // targeted re-runs.
  if (type === 'generate-note' && note.status === NoteStatus.DRAFT) {
    return { skipped: 'already_drafted' };
  }

  // Template resolution. If the note hasn't been assigned a template yet
  // (typical flow until the clinician picks one in /review), fall back to
  // the first preset template for the note's division. Templates seeded in
  // Commit 10.
  let template = note.template;
  let sectionSchema = template?.sectionSchema as { sections: NoteSectionDef[] } | null;
  if (!template || !sectionSchema?.sections?.length) {
    let fallback = await prisma.noteTemplate.findFirst({
      where: { isPreset: true, division: note.division, visibility: 'PUBLIC' },
      orderBy: { createdAt: 'asc' },
    });
    if (!fallback && note.division === Division.MULTI) {
      // MULTI is an org-aggregate division — no dedicated preset is seeded
      // for it (and buildMasterPrompt already routes MULTI → MEDICAL).
      // Mirror that mapping here so a MULTI note can still pick up a draft.
      fallback = await prisma.noteTemplate.findFirst({
        where: { isPreset: true, division: Division.MEDICAL, visibility: 'PUBLIC' },
        orderBy: { createdAt: 'asc' },
      });
    }
    if (!fallback) {
      // No preset template for the division — mark the note INTERRUPTED so
      // /processing can surface this clearly to the clinician.
      await prisma.note.update({
        where: { id: noteId },
        data: {
          status: NoteStatus.INTERRUPTED,
          interruptedAt: new Date(),
          lastWorkerError: `No preset NoteTemplate found for division=${note.division}`,
        },
      });
      await writeAuditLog({
        orgId,
        action: 'NOTE_INTERRUPTED',
        resourceType: 'Note',
        resourceId: noteId,
        metadata: { worker: 'ai-generation', errorClass: 'NoTemplate' },
      });
      return { failed: 'no_template' };
    }
    template = fallback;
    sectionSchema = template.sectionSchema as { sections: NoteSectionDef[] };
    await prisma.note.update({
      where: { id: noteId },
      data: { templateId: template.id, templateVersion: template.version },
    });
    await writeAuditLog({
      orgId,
      action: 'NOTE_TEMPLATE_SELECTED',
      resourceType: 'Note',
      resourceId: noteId,
      metadata: { templateId: template.id, division: template.division, autoSelected: true },
    });
  }

  const sections = sectionSchema?.sections ?? [];
  if (!sections.length) {
    throw new Error(`Template ${template.id} has empty sectionSchema.sections`);
  }

  // Build the master prompt once; we'll re-use the user body across sections.
  const llm = getLLMService();
  const promptInput = {
    division: (template.division ?? note.division) as Division,
    transcriptClean: note.transcriptClean as TranscriptClean | null,
    template: {
      id: template.id,
      name: template.name,
      sections,
      promptHints: template.promptHints as Record<string, unknown> | null,
    },
    noteStyle: note.noteStyle,
    patient: projectPatientForPrompt(note.patient),
    episode: note.encounter?.episode
      ? projectEpisodeForPrompt(note.encounter.episode)
      : undefined,
    // priorContext (Unit 06 brief) not yet computed; explicitly null so the
    // prompt notes "first visit or brief not yet computed".
    priorContext: null,
  };
  const master = buildMasterPrompt(promptInput);

  if (type === 'regenerate-section') {
    return regenerateOne(job as Job<RegenerateSectionJob>, {
      noteId,
      orgId,
      sections,
      llm,
      master,
      promptInput,
    });
  }

  // ----- generate-note: loop every section -----
  await writeAuditLog({
    orgId,
    action: 'NOTE_GENERATION_STARTED',
    resourceType: 'Note',
    resourceId: noteId,
    metadata: {
      requestId,
      templateId: template.id,
      sectionCount: sections.length,
      // Sprint 0.12 — persona-pass audit metadata across every
      // AI-authored audit row so a regulator can query "what did Miss
      // Cleo do for this patient?" by persona version alone.
      personaVersion: PERSONA_VERSION,
    },
  });

  // Rule 1 (ATTESTATION) guard: with an empty transcript the LLM has no source
  // material, but the per-section prompt still says "REQUIRED — do not leave
  // empty". Observed: BH Risk Assessment produced a confident SI/HI denial
  // paragraph from zero audio. Short-circuit to a uniform placeholder per
  // section so the model never gets the chance to invent content.
  const transcriptClean = note.transcriptClean as TranscriptClean | null;
  const hasUsableTranscript = !!transcriptClean && transcriptClean.wordCount > 0;
  if (!hasUsableTranscript) {
    const nowIso = new Date().toISOString();
    for (const section of sections) {
      await mergeSectionIntoDraft(
        noteId,
        section.id,
        'No transcript captured for this encounter. This section cannot be drafted from source material. Re-record or paste a transcript, then regenerate this section.',
      );
      await markSectionStatus(noteId, section.id, {
        status: 'populated',
        lastGeneratedAt: nowIso,
      });
    }
    // Stamp inferenceLog._meta so /review can detect this exact case
    // and render <EmptyTranscriptBanner> with a re-record CTA, instead
    // of leaving the clinician staring at six identical placeholder
    // paragraphs. Pulled from AudioSegment so the banner copy can be
    // specific ("we captured 4 s of audio"). Best-effort lookup —
    // duration falls back to 0 if no segments exist (transcript-only
    // dev path).
    const segments = await prisma.audioSegment.findMany({
      where: { noteId, isDeleted: false },
      select: { durationMs: true, byteSize: true },
    });
    const durationMs = segments.reduce((sum, s) => sum + (s.durationMs ?? 0), 0);
    const byteSize = segments.reduce((sum, s) => sum + (s.byteSize ?? 0), 0);
    await markNoteEmptyTranscript(noteId, { durationMs, byteSize });

    await prisma.note.update({
      where: { id: noteId },
      data: { status: NoteStatus.DRAFT },
    });
    await writeAuditLog({
      orgId,
      action: 'NOTE_STATUS_TRANSITIONED',
      resourceType: 'Note',
      resourceId: noteId,
      metadata: { from: 'DRAFTING', to: 'DRAFT', via: 'ai-generation-worker' },
    });
    await writeAuditLog({
      orgId,
      action: 'NOTE_GENERATION_COMPLETED',
      resourceType: 'Note',
      resourceId: noteId,
      metadata: {
        sectionCount: sections.length,
        failedCount: 0,
        skipped: 'no_transcript',
        emptyTranscriptDurationMs: durationMs,
        emptyTranscriptByteSize: byteSize,
        personaVersion: PERSONA_VERSION,
      },
    });
    // Sprint 0 lockdown — even on the empty-transcript short-circuit
    // path, run the inline flag analyzer so the lifecycle stamps +
    // runCount advance consistently. With zero content the analyzer
    // produces no flags but the section-hash snapshot is captured
    // (all empty-string hashes) so the sign-route edited-since-analysis
    // gate has a baseline to diff against if the clinician later
    // edits a placeholder.
    await runInlineFlagAnalysis({ noteId, orgId, sectionCount: sections.length });

    // Sprint 0.13/0.14 — chain-enqueue Miss Cleo's case-router + state
    // refresh. Best-effort: a failure here MUST NOT fail the parent job
    // (BullMQ retries would re-walk the section loop and look like a
    // regeneration storm to /review).
    await fireChainEnqueues({ noteId, orgId, patientId: note.patientId, clinicianOrgUserId: note.clinicianOrgUserId });
    return { ok: true, sections: sections.length, failed: 0, skipped: 'no_transcript' };
  }

  let failedCount = 0;
  for (const section of sections) {
    await markSectionStatus(noteId, section.id, {
      status: 'generating',
      generationStartedAt: new Date().toISOString(),
    });
    try {
      const result = await llm.generate(
        master.system,
        buildSectionPrompt(master.user, section, promptInput.noteStyle),
        {
          phi: true,
          temperature: 0,
          jsonMode: true,
          requestId,
          // Unit 35 — cost rollup metering. Surface includes section id
          // so the per-surface breakdown can attribute spend to a
          // specific section (most expensive: assessment + plan).
          meter: { orgId, noteId, surface: `worker.note-generation.${section.id}` },
        },
      );
      const content = extractContent(result.text, section.id);
      await mergeSectionIntoDraft(noteId, section.id, content);
      await markSectionStatus(noteId, section.id, {
        status: 'populated',
        lastGeneratedAt: new Date().toISOString(),
        model: result.model,
        latencyMs: result.latencyMs,
        tokensIn: result.tokensIn,
        tokensOut: result.tokensOut,
      });
      await recordSectionAttempt(noteId, { latencyMs: result.latencyMs, success: true });
      await writeAuditLog({
        orgId,
        action: 'SECTION_GENERATED',
        resourceType: 'Note',
        resourceId: noteId,
        metadata: {
          sectionId: section.id,
          model: result.model,
          latencyMs: result.latencyMs,
          tokensIn: result.tokensIn,
          tokensOut: result.tokensOut,
          stub: result.stub ?? false,
          personaVersion: PERSONA_VERSION,
        },
      });
    } catch (err) {
      failedCount++;
      const message = err instanceof Error ? `${err.name}: ${err.message}` : String(err);
      await markSectionStatus(noteId, section.id, {
        status: 'failed',
        error: { code: 'GENERATION_FAILED', message: message.slice(0, 300) },
      });
      await recordSectionAttempt(noteId, { latencyMs: 0, success: false });
      await writeAuditLog({
        orgId,
        action: 'SECTION_GENERATION_FAILED',
        resourceType: 'Note',
        resourceId: noteId,
        metadata: { sectionId: section.id, errorClass: err instanceof Error ? err.name : 'Unknown' },
      });
      // Continue with the next section — partial drafts are still useful to
      // the clinician + they can retry the failed section from /review.
    }
  }

  // Sprint 0 lockdown — run #1 of the flag analyzer (Haiku) INLINE
  // at the tail of generate-note, BEFORE flipping status to DRAFT.
  // The /review page is gated on DRAFT, so by the time the
  // clinician can route there, the initial flag set is already
  // populated. Failures degrade gracefully — the note still flips
  // to DRAFT and the clinician sees a banner; the retry budget is
  // still consumed so the retry-loop logic stays consistent.
  await runInlineFlagAnalysis({ noteId, orgId, sectionCount: sections.length });

  await prisma.note.update({
    where: { id: noteId },
    data: { status: NoteStatus.DRAFT },
  });
  await writeAuditLog({
    orgId,
    action: 'NOTE_STATUS_TRANSITIONED',
    resourceType: 'Note',
    resourceId: noteId,
    metadata: { from: 'DRAFTING', to: 'DRAFT', via: 'ai-generation-worker' },
  });
  await writeAuditLog({
    orgId,
    action: 'NOTE_GENERATION_COMPLETED',
    resourceType: 'Note',
    resourceId: noteId,
    metadata: {
      sectionCount: sections.length,
      failedCount,
      personaVersion: PERSONA_VERSION,
    },
  });

  // Sprint 0.13/0.14 — chain-enqueue Miss Cleo's case-router + state
  // refresh. Best-effort: a failure here MUST NOT fail the parent job
  // (BullMQ retries would re-walk the section loop and look like a
  // regeneration storm to /review).
  await fireChainEnqueues({ noteId, orgId, patientId: note.patientId, clinicianOrgUserId: note.clinicianOrgUserId });

  return { ok: true, sections: sections.length, failed: failedCount };
}

/**
 * Sprint 0 lockdown — inline analyzer call invoked by generate-note
 * BEFORE the DRAFT flip. Failure is caught + audited; the parent
 * pipeline always proceeds (the clinician must be able to land on
 * /review even when the analyzer is degraded).
 *
 * Stamps the lifecycle (flagAnalysisStartedAt) in a transaction-y
 * preamble — the worker's own finally block in runFlagAnalysisCore
 * advances flagAnalysisCompletedAt + bumps runCount.
 */
async function runInlineFlagAnalysis(args: {
  noteId: string;
  orgId: string;
  sectionCount: number;
}): Promise<void> {
  const { noteId, orgId } = args;
  const inlineReqId = randomBytes(8).toString('hex');

  // Stamp the lifecycle anchor BEFORE invoking the core so any
  // concurrent sign attempt sees `flag_analysis_pending` and refuses
  // 409 (existing gate in sign route). The core's `finally` will
  // stamp `flagAnalysisCompletedAt = now` so the gate clears
  // deterministically.
  try {
    await prisma.note.update({
      where: { id: noteId },
      data: {
        flagAnalysisStartedAt: new Date(),
        flagAnalysisCompletedAt: null,
      },
    });
  } catch (err) {
    console.warn(
      `[ai-generation] inline-flag-analyze startedAt stamp failed for ${noteId}:`,
      err instanceof Error ? err.message : err,
    );
    // Fall through — we still try to run the analyzer.
  }

  try {
    const { runFlagAnalysisCore } = await import('./analyze-flags-handler');
    const result = await runFlagAnalysisCore({
      noteId,
      orgId,
      requestId: `auto:${inlineReqId}`,
      runOrigin: 'AUTO_ON_DRAFT',
    });
    // Success path audit happens inside runFlagAnalysisCore via
    // FLAGS_AUTO_ANALYZED_ON_DRAFT. Skipped-cap is impossible here
    // (runCount starts at 0 on a fresh note); skipped:no_template /
    // no_sections are degenerate cases — we don't double-audit.
    if ('skipped' in result) {
      console.warn(
        `[ai-generation] inline-flag-analyze skipped for ${noteId}: ${result.skipped}`,
      );
    }
  } catch (err) {
    // Analyzer threw an unhandled error — the core's finally already
    // stamped completedAt + (possibly) bumped runCount. Audit the
    // failure so the clinician's "Flag analysis unavailable" banner
    // is reproducible from the audit trail.
    console.warn(
      `[ai-generation] inline-flag-analyze threw for ${noteId}:`,
      err instanceof Error ? err.message : err,
    );
    try {
      await writeAuditLog({
        orgId,
        action: 'FLAGS_AUTO_ANALYSIS_FAILED',
        resourceType: 'Note',
        resourceId: noteId,
        metadata: {
          errorClass: err instanceof Error ? err.name : 'Unknown',
          errorMessage: err instanceof Error ? err.message.slice(0, 300) : String(err).slice(0, 300),
        },
      });
    } catch {
      // Audit write failed too — give up silently. The clinician will
      // still see the "unavailable" banner from the empty flag set.
    }
  }
}

async function fireChainEnqueues(args: {
  noteId: string;
  orgId: string;
  patientId: string;
  clinicianOrgUserId: string;
}): Promise<void> {
  try {
    await enqueueCaseRouterJob({ noteId: args.noteId, orgId: args.orgId });
  } catch (err) {
    console.error(
      `[ai-generation] enqueueCaseRouterJob failed for note ${args.noteId}:`,
      err instanceof Error ? err.message : err,
    );
  }
  try {
    await enqueueCleoStateRefresh({
      orgId: args.orgId,
      patientId: args.patientId,
      clinicianOrgUserId: args.clinicianOrgUserId,
    });
  } catch (err) {
    console.error(
      `[ai-generation] enqueueCleoStateRefresh failed for note ${args.noteId}:`,
      err instanceof Error ? err.message : err,
    );
  }
}

async function regenerateOne(
  job: Job<RegenerateSectionJob>,
  ctx: {
    noteId: string;
    orgId: string;
    sections: NoteSectionDef[];
    llm: ReturnType<typeof getLLMService>;
    master: { system: string; user: string };
    promptInput: { noteStyle: string };
  },
) {
  const { noteId, orgId, sections, llm, master } = ctx;
  const { sectionId, requestId, triggeredByUserId, overwroteEdited } = job.data;
  const section = sections.find((s) => s.id === sectionId);
  if (!section) {
    throw new Error(`regenerate-section: section ${sectionId} not in template`);
  }

  // Snapshot the PREVIOUS content BEFORE we mark status=generating + overwrite.
  // Unit 10: the diff dialog renders this against the new content so the
  // clinician can confirm "what changed."
  const beforeNote = await prisma.note.findUnique({
    where: { id: noteId },
    select: { draftJson: true },
  });
  const beforeDraft = (beforeNote?.draftJson as Record<string, { content: string }> | null) ?? {};
  const previousContent = beforeDraft[sectionId]?.content;

  await markSectionStatus(noteId, sectionId, {
    status: 'generating',
    generationStartedAt: new Date().toISOString(),
  });

  try {
    const result = await llm.generate(
      master.system,
      buildSectionPrompt(master.user, section, ctx.promptInput.noteStyle),
      {
        phi: true,
        temperature: 0,
        jsonMode: true,
        requestId,
        // Unit 35 — cost rollup metering on section regen.
        meter: { orgId, noteId, surface: `worker.section-regen.${sectionId}` },
      },
    );
    const content = extractContent(result.text, sectionId);
    await mergeSectionIntoDraft(noteId, sectionId, content);
    await markSectionStatus(noteId, sectionId, {
      status: 'populated',
      lastGeneratedAt: new Date().toISOString(),
      model: result.model,
      latencyMs: result.latencyMs,
      tokensIn: result.tokensIn,
      tokensOut: result.tokensOut,
    });
    await appendRegeneration(noteId, {
      sectionId,
      requestId,
      triggeredByUserId,
      at: new Date().toISOString(),
      overwroteEdited: !!overwroteEdited,
      previousContent,
    });
    await recordSectionAttempt(noteId, { latencyMs: result.latencyMs, success: true });
    await writeAuditLog({
      orgId,
      action: 'SECTION_REGENERATED',
      resourceType: 'Note',
      resourceId: noteId,
      metadata: {
        sectionId,
        requestId,
        model: result.model,
        latencyMs: result.latencyMs,
        overwroteEdited: !!overwroteEdited,
      },
    });
    return { ok: true, sectionId };
  } catch (err) {
    const message = err instanceof Error ? `${err.name}: ${err.message}` : String(err);
    await markSectionStatus(noteId, sectionId, {
      status: 'failed',
      error: { code: 'GENERATION_FAILED', message: message.slice(0, 300) },
    });
    await recordSectionAttempt(noteId, { latencyMs: 0, success: false });
    await writeAuditLog({
      orgId,
      action: 'SECTION_GENERATION_FAILED',
      resourceType: 'Note',
      resourceId: noteId,
      metadata: { sectionId, errorClass: err instanceof Error ? err.name : 'Unknown' },
    });
    throw err;
  }
}

/**
 * Parse the JSON the model returned. Bedrock's text response (when jsonMode
 * is honored at the prompt layer) is a JSON object with { sectionId, content }.
 * If the model returned plain text by mistake (stub mode JSON-mode does
 * return JSON; real Bedrock may not always), we fall back to using the raw
 * text as content.
 */
function extractContent(rawText: string, sectionId: string): string {
  const trimmed = stripJsonFence(rawText);
  try {
    const parsed = JSON.parse(trimmed) as { content?: string; sectionId?: string };
    if (typeof parsed.content === 'string') return parsed.content;
  } catch {
    // Not JSON — fall through to raw text.
  }
  // Defensive: if the parsed object exists but the sectionId is wrong, still
  // accept the content (the model knew which section it was writing).
  return trimmed.length > 0 ? trimmed : `[empty section ${sectionId}]`;
}

// dummy use to silence unused-import warning if Prisma generation tweaks types
export const __schemaTouch = (_p: Prisma.JsonValue | null = null) => _p;
