import type { Job } from 'bullmq';
import { Prisma, NoteStatus, Division } from '@prisma/client';

import { prisma } from '@/lib/prisma';
import { writeAuditLog } from '@/lib/audit/log';
import { enqueueCaseRouterJob } from '@/lib/queue';
import { getLLMService } from '@/services/llm';
import { buildMasterPrompt, buildSectionPrompt, type NoteSectionDef } from '@/lib/notes/build-prompt';
import { projectPatientForPrompt, projectEpisodeForPrompt } from '@/lib/notes/projections';
import { PERSONA_VERSION } from '@/services/copilot/persona';
import {
  markSectionStatus,
  appendRegeneration,
  mergeSectionIntoDraft,
  recordSectionAttempt,
} from '@/lib/notes/section-status';
import type { TranscriptClean } from '@/services/transcription';

type GenerateNoteJob = {
  noteId: string;
  orgId: string;
  type: 'generate-note';
  requestId: string;
};

type RegenerateSectionJob = {
  noteId: string;
  orgId: string;
  type: 'regenerate-section';
  requestId: string;
  sectionId: string;
  triggeredByUserId?: string;
  overwroteEdited?: boolean;
};

type AnalyzeFlagsJob = {
  noteId: string;
  orgId: string;
  type: 'analyze-flags';
  requestId: string;
};

type AiGenerationJob = GenerateNoteJob | RegenerateSectionJob | AnalyzeFlagsJob;

/**
 * ai-generation worker (spec §E).
 *
 * Two job types share this handler via the type discriminator:
 *
 *   1. generate-note — loops over template.sectionSchema.sections, generates
 *      each section via LLM (PHI guard runs), marks _sectionStatus per
 *      section, merges content into draftJson. On success: flips DRAFTING
 *      → DRAFT and audits NOTE_GENERATION_COMPLETED. A single failed
 *      section doesn't tank the whole job — that section gets status
 *      'failed' and the loop continues.
 *
 *   2. regenerate-section — single section. Marks generating → populated,
 *      replaces only the target key in draftJson, appends a _regenerations
 *      entry capturing who/when/what.
 *
 * Anti-regression rule 3: refuses if Note.status === SIGNED. finalJson
 * is owned exclusively by the sign route (Commit 8).
 *
 * Idempotent: queue.ts uses stable jobIds so duplicate enqueues collapse.
 * The handler is also safe to retry — already-populated sections are
 * regenerated by generate-note (which is OK; final state is the same).
 */
export async function handle(job: Job<AiGenerationJob>) {
  // Unit 14: analyze-flags has its own load path (no patient/episode
  // projections needed, and the writes target ReviewFlag not draftJson).
  // Delegate before the heavy load below.
  if (job.data.type === 'analyze-flags') {
    const mod = await import('./analyze-flags-handler');
    return mod.handleAnalyzeFlags(job as unknown as Job<AnalyzeFlagsJob>);
  }

  const { noteId, orgId, type, requestId } = job.data;

  const note = await prisma.note.findFirst({
    where: { id: noteId, orgId },
    include: {
      template: true,
      patient: true,
      encounter: { include: { episode: { include: { department: true, goals: true } } } },
    },
  });
  if (!note) {
    console.warn(`[ai-generation] note ${noteId} not found — dropping`);
    return { skipped: 'not_found' };
  }
  if (note.status === NoteStatus.SIGNED) {
    return { skipped: 'signed' };
  }

  // Template resolution. If the note hasn't been assigned a template yet
  // (typical flow until the clinician picks one in /review), fall back to
  // the first preset template for the note's division. Templates seeded in
  // Commit 10.
  let template = note.template;
  let sectionSchema = template?.sectionSchema as { sections: NoteSectionDef[] } | null;
  if (!template || !sectionSchema?.sections?.length) {
    let fallback = await prisma.noteTemplate.findFirst({
      where: { isPreset: true, division: note.division, visibility: 'PUBLIC' },
      orderBy: { createdAt: 'asc' },
    });
    if (!fallback && note.division === Division.MULTI) {
      // MULTI is an org-aggregate division — no dedicated preset is seeded
      // for it (and buildMasterPrompt already routes MULTI → MEDICAL).
      // Mirror that mapping here so a MULTI note can still pick up a draft.
      fallback = await prisma.noteTemplate.findFirst({
        where: { isPreset: true, division: Division.MEDICAL, visibility: 'PUBLIC' },
        orderBy: { createdAt: 'asc' },
      });
    }
    if (!fallback) {
      // No preset template for the division — mark the note INTERRUPTED so
      // /processing can surface this clearly to the clinician.
      await prisma.note.update({
        where: { id: noteId },
        data: {
          status: NoteStatus.INTERRUPTED,
          interruptedAt: new Date(),
          lastWorkerError: `No preset NoteTemplate found for division=${note.division}`,
        },
      });
      await writeAuditLog({
        orgId,
        action: 'NOTE_INTERRUPTED',
        resourceType: 'Note',
        resourceId: noteId,
        metadata: { worker: 'ai-generation', errorClass: 'NoTemplate' },
      });
      return { failed: 'no_template' };
    }
    template = fallback;
    sectionSchema = template.sectionSchema as { sections: NoteSectionDef[] };
    await prisma.note.update({
      where: { id: noteId },
      data: { templateId: template.id, templateVersion: template.version },
    });
    await writeAuditLog({
      orgId,
      action: 'NOTE_TEMPLATE_SELECTED',
      resourceType: 'Note',
      resourceId: noteId,
      metadata: { templateId: template.id, division: template.division, autoSelected: true },
    });
  }

  const sections = sectionSchema?.sections ?? [];
  if (!sections.length) {
    throw new Error(`Template ${template.id} has empty sectionSchema.sections`);
  }

  // Build the master prompt once; we'll re-use the user body across sections.
  const llm = getLLMService();
  const promptInput = {
    division: (template.division ?? note.division) as Division,
    transcriptClean: note.transcriptClean as TranscriptClean | null,
    template: {
      id: template.id,
      name: template.name,
      sections,
      promptHints: template.promptHints as Record<string, unknown> | null,
    },
    noteStyle: note.noteStyle,
    patient: projectPatientForPrompt(note.patient),
    episode: note.encounter?.episode
      ? projectEpisodeForPrompt(note.encounter.episode)
      : undefined,
    // priorContext (Unit 06 brief) not yet computed; explicitly null so the
    // prompt notes "first visit or brief not yet computed".
    priorContext: null,
  };
  const master = buildMasterPrompt(promptInput);

  if (type === 'regenerate-section') {
    return regenerateOne(job as Job<RegenerateSectionJob>, {
      noteId,
      orgId,
      sections,
      llm,
      master,
      promptInput,
    });
  }

  // ----- generate-note: loop every section -----
  await writeAuditLog({
    orgId,
    action: 'NOTE_GENERATION_STARTED',
    resourceType: 'Note',
    resourceId: noteId,
    metadata: {
      requestId,
      templateId: template.id,
      sectionCount: sections.length,
      // Sprint 0.12 — persona-pass audit metadata across every
      // AI-authored audit row so a regulator can query "what did Miss
      // Cleo do for this patient?" by persona version alone.
      personaVersion: PERSONA_VERSION,
    },
  });

  // Rule 1 (ATTESTATION) guard: with an empty transcript the LLM has no source
  // material, but the per-section prompt still says "REQUIRED — do not leave
  // empty". Observed: BH Risk Assessment produced a confident SI/HI denial
  // paragraph from zero audio. Short-circuit to a uniform placeholder per
  // section so the model never gets the chance to invent content.
  const transcriptClean = note.transcriptClean as TranscriptClean | null;
  const hasUsableTranscript = !!transcriptClean && transcriptClean.wordCount > 0;
  if (!hasUsableTranscript) {
    const nowIso = new Date().toISOString();
    for (const section of sections) {
      await mergeSectionIntoDraft(
        noteId,
        section.id,
        'No transcript captured for this encounter. This section cannot be drafted from source material. Re-record or paste a transcript, then regenerate this section.',
      );
      await markSectionStatus(noteId, section.id, {
        status: 'populated',
        lastGeneratedAt: nowIso,
      });
    }
    await prisma.note.update({
      where: { id: noteId },
      data: { status: NoteStatus.DRAFT },
    });
    await writeAuditLog({
      orgId,
      action: 'NOTE_STATUS_TRANSITIONED',
      resourceType: 'Note',
      resourceId: noteId,
      metadata: { from: 'DRAFTING', to: 'DRAFT', via: 'ai-generation-worker' },
    });
    await writeAuditLog({
      orgId,
      action: 'NOTE_GENERATION_COMPLETED',
      resourceType: 'Note',
      resourceId: noteId,
      metadata: {
        sectionCount: sections.length,
        failedCount: 0,
        skipped: 'no_transcript',
        personaVersion: PERSONA_VERSION,
      },
    });
    // Sprint 0.13 — chain-enqueue Miss Cleo's case-router. Same pattern as
    // enqueueNoteBriefJob from the sign route. Idempotent on noteId
    // (queue.ts) so a retried completion collapses to one Redis entry.
    await enqueueCaseRouterJob({ noteId, orgId });
    return { ok: true, sections: sections.length, failed: 0, skipped: 'no_transcript' };
  }

  let failedCount = 0;
  for (const section of sections) {
    await markSectionStatus(noteId, section.id, {
      status: 'generating',
      generationStartedAt: new Date().toISOString(),
    });
    try {
      const result = await llm.generate(
        master.system,
        buildSectionPrompt(master.user, section, promptInput.noteStyle),
        {
          phi: true,
          temperature: 0,
          jsonMode: true,
          requestId,
          // Unit 35 — cost rollup metering. Surface includes section id
          // so the per-surface breakdown can attribute spend to a
          // specific section (most expensive: assessment + plan).
          meter: { orgId, noteId, surface: `worker.note-generation.${section.id}` },
        },
      );
      const content = extractContent(result.text, section.id);
      await mergeSectionIntoDraft(noteId, section.id, content);
      await markSectionStatus(noteId, section.id, {
        status: 'populated',
        lastGeneratedAt: new Date().toISOString(),
        model: result.model,
        latencyMs: result.latencyMs,
        tokensIn: result.tokensIn,
        tokensOut: result.tokensOut,
      });
      await recordSectionAttempt(noteId, { latencyMs: result.latencyMs, success: true });
      await writeAuditLog({
        orgId,
        action: 'SECTION_GENERATED',
        resourceType: 'Note',
        resourceId: noteId,
        metadata: {
          sectionId: section.id,
          model: result.model,
          latencyMs: result.latencyMs,
          tokensIn: result.tokensIn,
          tokensOut: result.tokensOut,
          stub: result.stub ?? false,
          personaVersion: PERSONA_VERSION,
        },
      });
    } catch (err) {
      failedCount++;
      const message = err instanceof Error ? `${err.name}: ${err.message}` : String(err);
      await markSectionStatus(noteId, section.id, {
        status: 'failed',
        error: { code: 'GENERATION_FAILED', message: message.slice(0, 300) },
      });
      await recordSectionAttempt(noteId, { latencyMs: 0, success: false });
      await writeAuditLog({
        orgId,
        action: 'SECTION_GENERATION_FAILED',
        resourceType: 'Note',
        resourceId: noteId,
        metadata: { sectionId: section.id, errorClass: err instanceof Error ? err.name : 'Unknown' },
      });
      // Continue with the next section — partial drafts are still useful to
      // the clinician + they can retry the failed section from /review.
    }
  }

  await prisma.note.update({
    where: { id: noteId },
    data: { status: NoteStatus.DRAFT },
  });
  await writeAuditLog({
    orgId,
    action: 'NOTE_STATUS_TRANSITIONED',
    resourceType: 'Note',
    resourceId: noteId,
    metadata: { from: 'DRAFTING', to: 'DRAFT', via: 'ai-generation-worker' },
  });
  await writeAuditLog({
    orgId,
    action: 'NOTE_GENERATION_COMPLETED',
    resourceType: 'Note',
    resourceId: noteId,
    metadata: {
      sectionCount: sections.length,
      failedCount,
      personaVersion: PERSONA_VERSION,
    },
  });

  // Sprint 0.13 — chain-enqueue Miss Cleo's case-router so the review
  // screen can render her routing proposal at the top. Idempotent on
  // noteId (queue.ts) so a retried completion collapses to one Redis
  // entry. Same pattern as enqueueNoteBriefJob from the sign route.
  await enqueueCaseRouterJob({ noteId, orgId });

  return { ok: true, sections: sections.length, failed: failedCount };
}

async function regenerateOne(
  job: Job<RegenerateSectionJob>,
  ctx: {
    noteId: string;
    orgId: string;
    sections: NoteSectionDef[];
    llm: ReturnType<typeof getLLMService>;
    master: { system: string; user: string };
    promptInput: { noteStyle: string };
  },
) {
  const { noteId, orgId, sections, llm, master } = ctx;
  const { sectionId, requestId, triggeredByUserId, overwroteEdited } = job.data;
  const section = sections.find((s) => s.id === sectionId);
  if (!section) {
    throw new Error(`regenerate-section: section ${sectionId} not in template`);
  }

  // Snapshot the PREVIOUS content BEFORE we mark status=generating + overwrite.
  // Unit 10: the diff dialog renders this against the new content so the
  // clinician can confirm "what changed."
  const beforeNote = await prisma.note.findUnique({
    where: { id: noteId },
    select: { draftJson: true },
  });
  const beforeDraft = (beforeNote?.draftJson as Record<string, { content: string }> | null) ?? {};
  const previousContent = beforeDraft[sectionId]?.content;

  await markSectionStatus(noteId, sectionId, {
    status: 'generating',
    generationStartedAt: new Date().toISOString(),
  });

  try {
    const result = await llm.generate(
      master.system,
      buildSectionPrompt(master.user, section, ctx.promptInput.noteStyle),
      {
        phi: true,
        temperature: 0,
        jsonMode: true,
        requestId,
        // Unit 35 — cost rollup metering on section regen.
        meter: { orgId, noteId, surface: `worker.section-regen.${sectionId}` },
      },
    );
    const content = extractContent(result.text, sectionId);
    await mergeSectionIntoDraft(noteId, sectionId, content);
    await markSectionStatus(noteId, sectionId, {
      status: 'populated',
      lastGeneratedAt: new Date().toISOString(),
      model: result.model,
      latencyMs: result.latencyMs,
      tokensIn: result.tokensIn,
      tokensOut: result.tokensOut,
    });
    await appendRegeneration(noteId, {
      sectionId,
      requestId,
      triggeredByUserId,
      at: new Date().toISOString(),
      overwroteEdited: !!overwroteEdited,
      previousContent,
    });
    await recordSectionAttempt(noteId, { latencyMs: result.latencyMs, success: true });
    await writeAuditLog({
      orgId,
      action: 'SECTION_REGENERATED',
      resourceType: 'Note',
      resourceId: noteId,
      metadata: {
        sectionId,
        requestId,
        model: result.model,
        latencyMs: result.latencyMs,
        overwroteEdited: !!overwroteEdited,
      },
    });
    return { ok: true, sectionId };
  } catch (err) {
    const message = err instanceof Error ? `${err.name}: ${err.message}` : String(err);
    await markSectionStatus(noteId, sectionId, {
      status: 'failed',
      error: { code: 'GENERATION_FAILED', message: message.slice(0, 300) },
    });
    await recordSectionAttempt(noteId, { latencyMs: 0, success: false });
    await writeAuditLog({
      orgId,
      action: 'SECTION_GENERATION_FAILED',
      resourceType: 'Note',
      resourceId: noteId,
      metadata: { sectionId, errorClass: err instanceof Error ? err.name : 'Unknown' },
    });
    throw err;
  }
}

/**
 * Parse the JSON the model returned. Bedrock's text response (when jsonMode
 * is honored at the prompt layer) is a JSON object with { sectionId, content }.
 * If the model returned plain text by mistake (stub mode JSON-mode does
 * return JSON; real Bedrock may not always), we fall back to using the raw
 * text as content.
 */
function extractContent(rawText: string, sectionId: string): string {
  let trimmed = rawText.trim();
  // Strip markdown code fence if present. Claude and many other LLMs wrap
  // JSON in ```json … ``` (or ``` … ```) even when asked for raw JSON via
  // jsonMode. Without unwrapping, JSON.parse fails and the entire fenced
  // block (including the ```json header and the inner { sectionId, content }
  // wrapper) ends up rendered to the clinician as raw JSON in /review.
  const fenceMatch = trimmed.match(/^```(?:json)?\s*\r?\n([\s\S]*?)\r?\n```$/);
  if (fenceMatch?.[1]) {
    trimmed = fenceMatch[1].trim();
  }
  // Try JSON parse.
  try {
    const parsed = JSON.parse(trimmed) as { content?: string; sectionId?: string };
    if (typeof parsed.content === 'string') return parsed.content;
  } catch {
    // Not JSON — fall through to raw text.
  }
  // Defensive: if the parsed object exists but the sectionId is wrong, still
  // accept the content (the model knew which section it was writing).
  return trimmed.length > 0 ? trimmed : `[empty section ${sectionId}]`;
}

// dummy use to silence unused-import warning if Prisma generation tweaks types
export const __schemaTouch = (_p: Prisma.JsonValue | null = null) => _p;
